name: Create Jira Issue on Build Failure

on:
  workflow_run:
    workflows: ["ticket.yml"]
    types:
      - completed
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get commit message
        id: get-commit-message
        run: echo "COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.event.workflow_run.head_commit.id }})" >> $GITHUB_ENV

      - name: Create Jira issue
        run: |
          curl --location '${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue' \
          --header 'Content-Type:application/json' \
          --header 'Authorization:Basic YW5qYWxpLmphZGhhdkBhbXJ1dHNvZnR3YXJlLmNvbTpBVEFUVDN4RmZHRjA1YzdFbHY3LXI0VkFZTXk0LXllQlZyR1F0R0huTVFRY1hWdFZBR0R5THJiaHhUT01nUlBuVjZXY1NIeGpfQWtnWXEtT2ZBQkRRRlBTRGFrdTVYTF9xNG10UVBzWGpoWXllN3E2ZjVQV0ZpSmtzMzJBWXpZdmpYNS00SXkzYW1sSnlPTElGaXpDeldSem1OVnJRXzF6THZGNTJ5ZmU1YXp5TF9ZZTRkeHFsTDA9OEVBMzVEQjc=' \
          --data '{
            "fields":{
              "description":"This issue is created by GitHub due to a build failure.",
              "issuetype":{
                "id":"10007"
              },
              "project":{
                "id":"10029"
              },
              "summary":"Build failed for commit: ${{ env.COMMIT_MESSAGE }}"
            }
          }'
