name: Create Jira Issue on Push
'on':
  - push
jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  

      - name: Create Jira issue    
        run: |
          curl --location 'JIRA_BASE_URL/rest/api/2/issue' \
          --header 'Content-Type:application/json' \
          --header 'Authorization: Basic $(echo -n $JIRA_API_TOKEN | base64)' \
          --data '{
            "fields":{
              "description":"Order entry fails when selecting supplier.",
              "issuetype":{
                "id":"10007"
              },
              "project":{
                "id":"10029"
              },
              "summary":"Main order flow broken"
            }
          }'
