name: Create Jira Issue on Push
'on':
  push:
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        env:
          JIRA_BASE_URL: '${{ secrets.JIRA_BASE_URL }}'
          JIRA_USER_EMAIL: '${{ secrets.JIRA_USER_EMAIL }}'
          JIRA_API_TOKEN: '${{ secrets.JIRA_API_TOKEN }}'
          
      - name: Create Jira Issue
        run: |
          curl --location "${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue" \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Basic ${{ secrets.JIRA_API_TOKEN }}' \
          --data '{
            "fields": {
              "description": "Order entry fails when selecting supplier.",
              "issuetype": {
                "id": "10007"
              },
              "project": {
                "id": "10029"
              },
              "summary": "Main order flow broken"
            }
          }'
