name: Create Jira Issue on Push

on: [push]

jobs:
  create-issue: 
    runs-on: ubuntu-latest
    steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create Jira Issue
      uses: atlassian/gajira-create@v3
      with:
        project: "JP"
        issuetype: "Bug"
        summary: "New issue from GitHub Actions"
        description: "This issue was created automatically via GitHub Actions."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
