name: Create Jira Issue on Push
'on':
  - push
jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  
        env:
          JIRA_BASE_URL: '${{ secrets.JIRA_BASE_URL }}'
          JIRA_USER_EMAIL: '${{ secrets.JIRA_USER_EMAIL }}'
          JIRA_API_TOKEN: '${{ secrets.JIRA_API_TOKEN }}'
      - name: Create Jira issue    
        run: |
          curl --location 'JIRA_BASE_URL/rest/api/2/issue' \
          --header 'Content-Type:application/json' \
          --header 'Authorization: Basic $(echo -n $JIRA_API_TOKEN | base64)' \
          --data '{
            "fields":{
              "description":"This issue is created by GitHub.",
              "issuetype":{
                "id":"10007"
              },
              "project":{
                "id":"10029"
              },
              "summary":"${{ github.event.head_commit.message }}"
            }
          }
